
if(DEFINED POLLY_LINUX_CMAKE_)
  return()
else()
  set(POLLY_LINUX_CMAKE_ 1)
endif()

if (NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux") 
  message(FATAL_ERROR "Incompatible System Toolchain, you are running the build on '${CMAKE_HOST_SYSTEM_NAME}' and this toolchain is made for 'Linux'.")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/compiler/clang.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/compiler/cuda.cmake")

include("${CMAKE_CURRENT_LIST_DIR}/flags/fpic.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/generator/ninja.cmake")
set (TIPI_CUDA_LAUNCHER "/usr/local/bin/tipi-cuda-driver" CACHE STRING "" FORCE)

set(
    CMAKE_CUDA_COMPILER_LAUNCHER
    "${TIPI_CUDA_LAUNCHER}"
    CACHE
    FILEPATH
    "CUDA compiler launcher"
    FORCE
)
set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
set(PARAVIEW_USE_PYTHON ON CACHE BOOL "" FORCE)
set(PARAVIEW_USE_MPI ON CACHE BOOL "" FORCE)
set(PARAVIEW_USE_CUDA ON CACHE BOOL "" FORCE)
set(VTK_USE_CUDA ON CACHE BOOL "" FORCE)
set(PARAVIEW_USE_VISKORES ON CACHE BOOL "" FORCE)

set(VTK_DEBUG_LEAKS ON CACHE BOOL "" FORCE)
set(PARAVIEW_BUILD_TESTING "WANT" CACHE STRING "" FORCE)
set(PARAVIEW_BUILD_VTK_TESTING "WANT" CACHE STRING "" FORCE)

set(VTK_SMP_IMPLEMENTATION_TYPE "TBB" CACHE STRING "" FORCE)

set(PARAVIEW_EXTRA_COMPILER_WARNINGS ON CACHE BOOL "" FORCE)
set(PARAVIEW_ENABLE_EXAMPLES ON CACHE BOOL "" FORCE)
set(PARAVIEW_BUILD_LEGACY_REMOVE ON CACHE BOOL "" FORCE)
set(PARAVIEW_ENABLE_EXTRA_BUILD_WARNINGS ON CACHE BOOL "" FORCE)
set(PARAVIEW_GENERATE_SPDX ON CACHE BOOL "" FORCE)
set(PARAVIEW_LINKER_FATAL_WARNINGS ON CACHE BOOL "" FORCE)

# Leave this OFF. The option is currently deprecated and auto-disabled.
set(PARAVIEW_ENABLE_NVPIPE OFF CACHE BOOL "" FORCE)

